// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 644 (Rhahk'Zor), 25 anchors over 327yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_644()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 644,
        {
            { -32.89f, -375.39f, 59.51f },
            { -51.13f, -370.35f, 56.03f },
            { -62.99f, -373.86f, 55.64f },
            { -59.14f, -369.68f, 55.78f },
            { -67.64f, -379.25f, 55.27f },
            { -62.37f, -377.46f, 55.02f },
            { -76.73f, -381.59f, 55.24f },
            { -98.72f, -373.68f, 58.73f },
            { -91.03f, -374.97f, 59.07f },
            { -100.72f, -391.09f, 58.11f },
            { -103.22f, -375.55f, 59.34f },
            { -99.57f, -391.65f, 58.44f },
            { -121.50f, -400.34f, 58.34f },
            { -129.62f, -395.46f, 59.16f },
            { -129.75f, -406.52f, 58.43f },
            { -139.34f, -412.57f, 58.85f },
            { -155.85f, -404.08f, 57.77f },
            { -161.84f, -402.49f, 57.61f },
            { -176.73f, -410.72f, 56.85f },
            { -171.64f, -406.13f, 57.11f },
            { -185.62f, -422.22f, 54.65f },
            { -191.77f, -444.14f, 54.31f },
            { -198.80f, -450.71f, 55.15f },
            { -194.37f, -450.40f, 55.06f },
            { -188.19f, -439.82f, 54.39f },
        });
}
