// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 34, boss 1717 (Hamhock), 10 anchors over 160yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute34_1717()
{
    DungeonClearRouteRegistry::Register(34, DUNGEON_DIFFICULTY_NORMAL, 1717,
        {
            { 54.23f, 0.28f, -18.34f },
            { 72.99f, -0.23f, -25.34f },
            { 89.80f, 2.85f, -25.61f },
            { 105.74f, 0.06f, -25.61f },
            { 125.54f, -3.28f, -25.61f },
            { 127.74f, -24.33f, -30.83f },
            { 128.32f, -41.61f, -33.98f },
            { 130.26f, -51.89f, -33.35f },
            { 118.01f, -77.99f, -33.94f },
            { 114.55f, -88.16f, -33.40f },
        });
}
