// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 34, boss 1696 (Targorr the Dread), 8 anchors over 114yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute34_1696()
{
    DungeonClearRouteRegistry::Register(34, DUNGEON_DIFFICULTY_NORMAL, 1696,
        {
            { 113.00f, -92.78f, -33.93f },
            { 120.97f, -75.97f, -33.94f },
            { 127.37f, -59.18f, -33.94f },
            { 129.17f, -42.64f, -33.94f },
            { 130.53f, -26.28f, -31.57f },
            { 130.66f, -18.19f, -28.55f },
            { 135.45f, -0.92f, -25.61f },
            { 154.29f, 0.92f, -25.61f },
        });
}
