// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 642 (Sneed's Shredder), 15 anchors over 208yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_642()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 642,
        {
            { -201.33f, -453.08f, 55.13f },
            { -185.57f, -452.76f, 54.57f },
            { -191.54f, -474.64f, 54.09f },
            { -197.44f, -490.74f, 53.94f },
            { -192.44f, -490.35f, 54.19f },
            { -203.75f, -512.53f, 52.84f },
            { -204.92f, -505.71f, 52.45f },
            { -221.64f, -500.31f, 49.54f },
            { -231.31f, -476.99f, 49.26f },
            { -235.40f, -482.59f, 49.25f },
            { -249.85f, -486.96f, 49.49f },
            { -273.06f, -483.92f, 49.61f },
            { -278.63f, -483.47f, 49.54f },
            { -289.66f, -495.27f, 50.69f },
            { -284.43f, -492.99f, 49.84f },
        });
}
