// GENERATED by DcRouteRecorder from a live clear — safe to edit by hand.
// Map 36, boss 1763 (Gilnid), 22 anchors over 301yd.
//
// The recorder samples the run leader every ~4yd and thins the leg to
// ~15yd anchors (corners preserved). Advance prefers a registered anchor
// route over the long-range router, so this file makes the walked path the
// path every later run takes.
#include "Ai/Dungeon/DungeonClear/Data/DungeonClearRouteRegistry.h"

void RegisterRecordedRoute36_1763()
{
    DungeonClearRouteRegistry::Register(36, DUNGEON_DIFFICULTY_NORMAL, 1763,
        {
            { -294.40f, -525.57f, 49.59f },
            { -286.78f, -554.62f, 49.41f },
            { -283.23f, -560.00f, 49.56f },
            { -294.67f, -560.88f, 49.12f },
            { -298.91f, -583.76f, 47.30f },
            { -298.10f, -589.18f, 48.34f },
            { -286.19f, -594.33f, 49.88f },
            { -266.93f, -581.66f, 50.28f },
            { -241.57f, -575.92f, 19.38f },
            { -230.23f, -563.67f, 19.96f },
            { -234.16f, -568.33f, 19.91f },
            { -225.99f, -581.52f, 20.88f },
            { -212.12f, -584.24f, 21.56f },
            { -223.60f, -574.32f, 21.65f },
            { -206.48f, -571.57f, 20.98f },
            { -200.46f, -572.22f, 20.98f },
            { -196.34f, -578.94f, 21.60f },
            { -203.12f, -574.05f, 21.56f },
            { -188.08f, -572.85f, 21.01f },
            { -186.69f, -556.00f, 19.87f },
            { -182.31f, -566.95f, 19.92f },
            { -193.58f, -568.16f, 21.62f },
        });
}
